// This file is auto-generated by IP_SETUP.sh
// Do not edit manually

import AsyncStorage from '@react-native-async-storage/async-storage';

// Set up the ML API URL in AsyncStorage
export async function setupMlApiUrl() {
  try {
    // Store the ML API URL in AsyncStorage
    await AsyncStorage.setItem('ml_api_url', 'http://192.168.29.142:5000/api');
    console.log('ML API URL set to: http://192.168.29.142:5000/api');
    return true;
  } catch (error) {
    console.error('Error setting ML API URL:', error);
    return false;
  }
}

// Call this function when the app starts
export default setupMlApiUrl;
